In [23]:
#coding=utf-8  
# import the necessary packages
from scipy.spatial import distance as dist
from imutils.video import FileVideoStream
from imutils.video import VideoStream
from imutils import face_utils
import numpy as np
import argparse
import imutils
import time
import dlib
import cv2

def eye_aspect_ratio(eye):
    # compute the euclidean distances between the two sets of
    # vertical eye landmarks (x, y)-coordinates
    A = dist.euclidean(eye[1], eye[5])
    B = dist.euclidean(eye[2], eye[4])
    # compute the euclidean distance between the horizontal
    # eye landmark (x, y)-coordinates
    C = dist.euclidean(eye[0], eye[3])
    # compute the eye aspect ratio
    ear = (A + B) / (2.0 * C)
    # return the eye aspect ratio
    return ear
# define two constants, one for the eye aspect ratio to indicate
# blink and then a second constant for the number of consecutive
# frames the eye must be below the threshold
EYE_AR_THRESH = 0.3
EYE_AR_CONSEC_FRAMES = 3
# initialize the frame counters and the total number of blinks
COUNTER = 0
TOTAL = 0
# Dlib 检测器和预测器
print("[INFO] loading facial landmark predictor...")
detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor("C:/Users/lll/Documents/hz/shape_predictor_68_face_landmarks.dat")
# grab the indexes of the facial landmarks for the left and
# right eye, respectively
(lStart, lEnd) = face_utils.FACIAL_LANDMARKS_IDXS["left_eye"]
(rStart, rEnd) = face_utils.FACIAL_LANDMARKS_IDXS["right_eye"]

# start the video stream thread
print("[INFO] starting video stream thread...")
vs = FileVideoStream("C:/Users/lll/Documents/hz/conda/images/video.mp4").start()
fileStream = True
# vs = VideoStream(src=0).start()
# vs = VideoStream(usePiCamera=True).start()
# fileStream = False
time.sleep(1.0)

# loop over frames from the video stream
while True:
    # if this is a file video stream, then we need to check if
    # there any more frames left in the buffer to process
    if fileStream and not vs.more():
        break

    # grab the frame from the threaded video file stream, resize
    # it, and convert it to grayscale
    # channels)
    frame = vs.read()
    frame = imutils.resize(frame, width = 900)
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # detect faces in the grayscale frame
    rects = detector(gray, 0)
    	# loop over the face detections
    for rect in rects:
        # determine the facial landmarks for the face region, then
        # convert the facial landmark (x, y)-coordinates to a NumPy
        # array
        shape = predictor(gray, rect)
        shape = face_utils.shape_to_np(shape)

        # extract the left and right eye coordinates, then use the
        # coordinates to compute the eye aspect ratio for both eyes
        leftEye = shape[lStart:lEnd]
        rightEye = shape[rStart:rEnd]
        leftEAR = eye_aspect_ratio(leftEye)
        rightEAR = eye_aspect_ratio(rightEye)

        # average the eye aspect ratio together for both eyes
        ear = (leftEAR + rightEAR) / 2.0
                # compute the convex hull for the left and right eye, then
        # visualize each of the eyes
        leftEyeHull = cv2.convexHull(leftEye) 
        rightEyeHull = cv2.convexHull(rightEye)
        cv2.drawContours(frame, [leftEyeHull], -1, (0, 255, 0), 1)
        cv2.drawContours(frame, [rightEyeHull], -1, (0, 255, 0), 1)

        # check to see if the eye aspect ratio is below the blink
        # threshold, and if so, increment the blink frame counter
        if ear < EYE_AR_THRESH:
            COUNTER += 1
 
        # otherwise, the eye aspect ratio is not below the blink
        # threshold
        else:
            if COUNTER >= EYE_AR_CONSEC_FRAMES:
                TOTAL += 1
 
        # reset the eye frame counter
            COUNTER = 0
                # draw the total number of blinks on the frame along with
        # the computed eye aspect ratio for the frame
        cv2.putText(frame, "Blinks: {}".format(TOTAL), (10, 30),
            cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)
        cv2.putText(frame, "EAR: {:.2f}".format(ear), (300, 30),
            cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)

    # show the frame
    cv2.imshow("Frame", frame)
    key = cv2.waitKey(1) & 0xFF

    # if the `q` key was pressed, break from the loop
    if key == ord("q"):
        break
 

cv2.destroyAllWindows()
vs.stop()

[INFO] loading facial landmark predictor...
[INFO] starting video stream thread...


AttributeError: 'NoneType' object has no attribute 'shape'

In [6]:
#!/usr/bin/env python
 
import cv2
import numpy as np
 
# Read Image
im = cv2.imread("C:/Users/lll/Documents/hz/conda/images/test2.jpg");
size = im.shape
     
#2D image points. If you change the image, you need to change vector
image_points = np.array([
                            (359, 391),     # Nose tip
                            (399, 561),     # Chin
                            (337, 297),     # Left eye left corner
                            (513, 301),     # Right eye right corne
                            (345, 465),     # Left Mouth corner
                            (453, 469)      # Right mouth corner
                        ], dtype="double")
 
# 3D model points.
model_points = np.array([
                            (0.0, 0.0, 0.0),             # Nose tip
                            (0.0, -330.0, -65.0),        # Chin
                            (-225.0, 170.0, -135.0),     # Left eye left corner
                            (225.0, 170.0, -135.0),      # Right eye right corne
                            (-150.0, -150.0, -125.0),    # Left Mouth corner
                            (150.0, -150.0, -125.0)      # Right mouth corner
                         
                        ])
 
 
# Camera internals
 
focal_length = size[1]
center = (size[1]/2, size[0]/2)
camera_matrix = np.array(
                         [[focal_length, 0, center[0]],
                         [0, focal_length, center[1]],
                         [0, 0, 1]], dtype = "double"
                         )
 
print ("Camera Matrix :\n {0}".format(camera_matrix))
 
dist_coeffs = np.zeros((4,1)) # Assuming no lens distortion
(success, rotation_vector, translation_vector) = cv2.solvePnP(model_points, image_points, camera_matrix, dist_coeffs, flags=cv2.SOLVEPNP_ITERATIVE)
 
print ("Rotation Vector:\n {0}".format(rotation_vector))
print ("Translation Vector:\n {0}".format(translation_vector))
 
 
# Project a 3D point (0, 0, 1000.0) onto the image plane.
# We use this to draw a line sticking out of the nose
 
 
(nose_end_point2D, jacobian) = cv2.projectPoints(np.array([(0.0, 0.0, 1000.0)]), rotation_vector, translation_vector, camera_matrix, dist_coeffs)
 
for p in image_points:
    cv2.circle(im, (int(p[0]), int(p[1])), 3, (0,0,255), -1)
 
 
p1 = ( int(image_points[0][0]), int(image_points[0][1]))
p2 = ( int(nose_end_point2D[0][0][0]), int(nose_end_point2D[0][0][1]))
 
cv2.line(im, p1, p2, (255,0,0), 2)
 
# Display image
cv2.imshow("Output", im)
cv2.waitKey(0)

Camera Matrix :
 [[500.   0. 250.]
 [  0. 500. 166.]
 [  0.   0.   1.]]
Rotation Vector:
 [[ 0.28864022]
 [-3.53529416]
 [ 0.35388637]]
Translation Vector:
 [[ -280.86665559]
 [ -471.67503905]
 [-1124.18819423]]


-1

In [1]:
#!/usr/bin/env python
 
import cv2
import numpy as np
import dlib
import time
import math

detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor("C:/Users/lll/Documents/hz/shape_predictor_68_face_landmarks.dat")
POINTS_NUM_LANDMARK = 68

# 获取最大的人脸
def _largest_face(dets):
    if len(dets) == 1:
        return 0

    face_areas = [ (det.right()-det.left())*(det.bottom()-det.top()) for det in dets]

    largest_area = face_areas[0]
    largest_index = 0
    for index in range(1, len(dets)):
        if face_areas[index] > largest_area :
            largest_index = index
            largest_area = face_areas[index]

    print("largest_face index is {} in {} faces".format(largest_index, len(dets)))

    return largest_index

# 从dlib的检测结果抽取姿态估计需要的点坐标
def get_image_points_from_landmark_shape(landmark_shape):
    if landmark_shape.num_parts != POINTS_NUM_LANDMARK:
        print("ERROR:landmark_shape.num_parts-{}".format(landmark_shape.num_parts))
        return -1, None
    
    #2D image points. If you change the image, you need to change vector
    image_points = np.array([
                                (landmark_shape.part(30).x, landmark_shape.part(30).y),     # Nose tip
                                (landmark_shape.part(8).x, landmark_shape.part(8).y),     # Chin
                                (landmark_shape.part(36).x, landmark_shape.part(36).y),     # Left eye left corner
                                (landmark_shape.part(45).x, landmark_shape.part(45).y),     # Right eye right corne
                                (landmark_shape.part(48).x, landmark_shape.part(48).y),     # Left Mouth corner
                                (landmark_shape.part(54).x, landmark_shape.part(54).y)      # Right mouth corner
                            ], dtype="double")

    return 0, image_points
    
# 用dlib检测关键点，返回姿态估计需要的几个点坐标
def get_image_points(img):
                            
    #gray = cv2.cvtColor( img, cv2.COLOR_BGR2GRAY )  # 图片调整为灰色
    dets = detector( img, 0 )

    if 0 == len( dets ):
        print( "ERROR: found no face" )
        return -1, None
    largest_index = _largest_face(dets)
    face_rectangle = dets[largest_index]

    landmark_shape = predictor(img, face_rectangle)

    return get_image_points_from_landmark_shape(landmark_shape)


# 获取旋转向量和平移向量                        
def get_pose_estimation(img_size, image_points ):
    # 3D model points.
    model_points = np.array([
                                (0.0, 0.0, 0.0),             # Nose tip
                                (0.0, -330.0, -65.0),        # Chin
                                (-225.0, 170.0, -135.0),     # Left eye left corner
                                (225.0, 170.0, -135.0),      # Right eye right corne
                                (-150.0, -150.0, -125.0),    # Left Mouth corner
                                (150.0, -150.0, -125.0)      # Right mouth corner
                             
                            ])
     
    # Camera internals
     
    focal_length = img_size[1]
    center = (img_size[1]/2, img_size[0]/2)
    camera_matrix = np.array(
                             [[focal_length, 0, center[0]],
                             [0, focal_length, center[1]],
                             [0, 0, 1]], dtype = "double"
                             )
     
    print("Camera Matrix :{}".format(camera_matrix))
     
    dist_coeffs = np.zeros((4,1)) # Assuming no lens distortion
    (success, rotation_vector, translation_vector) = cv2.solvePnP(model_points, image_points, camera_matrix, dist_coeffs, flags=cv2.SOLVEPNP_ITERATIVE )
 
    print("Rotation Vector:\n {}".format(rotation_vector))
    print("Translation Vector:\n {}".format(translation_vector))
    return success, rotation_vector, translation_vector, camera_matrix, dist_coeffs

# 从旋转向量转换为欧拉角
def get_euler_angle(rotation_vector):
    # calculate rotation angles
    theta = cv2.norm(rotation_vector, cv2.NORM_L2)
    
    # transformed to quaterniond
    w = math.cos(theta / 2)
    x = math.sin(theta / 2)*rotation_vector[0][0] / theta
    y = math.sin(theta / 2)*rotation_vector[1][0] / theta
    z = math.sin(theta / 2)*rotation_vector[2][0] / theta
    
    ysqr = y * y
    # pitch (x-axis rotation)
    t0 = 2.0 * (w * x + y * z)
    t1 = 1.0 - 2.0 * (x * x + ysqr)
    print('t0:{}, t1:{}'.format(t0, t1))
    pitch = math.atan2(t0, t1)
    
    # yaw (y-axis rotation)
    t2 = 2.0 * (w * y - z * x)
    if t2 > 1.0:
        t2 = 1.0
    if t2 < -1.0:
        t2 = -1.0
    yaw = math.asin(t2)
    
    # roll (z-axis rotation)
    t3 = 2.0 * (w * z + x * y)
    t4 = 1.0 - 2.0 * (ysqr + z * z)
    roll = math.atan2(t3, t4)
    
    print('pitch:{}, yaw:{}, roll:{}'.format(pitch, yaw, roll))
    
	# 单位转换：将弧度转换为度
    Y = int((pitch/math.pi)*180)
    X = int((yaw/math.pi)*180)
    Z = int((roll/math.pi)*180)
    
    return 0, Y, X, Z

def get_pose_estimation_in_euler_angle(landmark_shape, im_szie):
    try:
        ret, image_points = get_image_points_from_landmark_shape(landmark_shape)
        if ret != 0:
            print('get_image_points failed')
            return -1, None, None, None
    
        ret, rotation_vector, translation_vector, camera_matrix, dist_coeffs = get_pose_estimation(im_szie, image_points)
        if ret != True:
            print('get_pose_estimation failed')
            return -1, None, None, None
    
        ret, pitch, yaw, roll = get_euler_angle(rotation_vector)
        if ret != 0:
            print('get_euler_angle failed')
            return -1, None, None, None

        euler_angle_str = 'Y:{}, X:{}, Z:{}'.format(pitch, yaw, roll)
        print(euler_angle_str)
        return 0, pitch, yaw, roll
    
    except Exception as e:
        print('get_pose_estimation_in_euler_angle exception:{}'.format(e))
        return -1, None, None, None
        
if __name__ == '__main__':

    # rtsp://admin:ts123456@10.20.21.240:554
    #cap = cv2.VideoCapture(0)
    cap =cv2.VideoCapture("C:/Users/lll/Documents/hz/conda/images/video.mp4")
    while (cap.isOpened()):
        start_time = time.time()
        
        # Read Image
        ret, im = cap.read()
        if ret != True:
            print('read frame failed')
            continue
        size = im.shape
        
        if size[0] > 700:
            h = size[0] / 3
            w = size[1] / 3
            im = cv2.resize( im, (int( w ), int( h )), interpolation=cv2.INTER_CUBIC )
            size = im.shape
     
        ret, image_points = get_image_points(im)
        if ret != 0:
            print('get_image_points failed')
            continue
        
        ret, rotation_vector, translation_vector, camera_matrix, dist_coeffs = get_pose_estimation(size, image_points)
        if ret != True:
            print('get_pose_estimation failed')
            continue
        used_time = time.time() - start_time
        print("used_time:{} sec".format(round(used_time, 3)))
        
        ret, pitch, yaw, roll = get_euler_angle(rotation_vector)
        euler_angle_str = 'Y:{}, X:{}, Z:{}'.format(pitch, yaw, roll)
        print(euler_angle_str)
        
        # Project a 3D point (0, 0, 1000.0) onto the image plane.
        # We use this to draw a line sticking out of the nose
         
        (nose_end_point2D, jacobian) = cv2.projectPoints(np.array([(0.0, 0.0, 1000.0)]), rotation_vector, translation_vector, camera_matrix, dist_coeffs)
         
        for p in image_points:
            cv2.circle(im, (int(p[0]), int(p[1])), 3, (0,0,255), -1)
         
         
        p1 = ( int(image_points[0][0]), int(image_points[0][1]))
        p2 = ( int(nose_end_point2D[0][0][0]), int(nose_end_point2D[0][0][1]))
         
        cv2.line(im, p1, p2, (255,0,0), 2)
         
        # Display image
        #cv2.putText( im, str(rotation_vector), (0, 100), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 255), 1 )
        cv2.putText( im, euler_angle_str, (0, 120), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 255), 1 )
        cv2.imshow("Output", im)
        cv2.waitKey(1)


Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.84418299]
 [ 0.02927406]
 [-1.37775196]]
Translation Vector:
 [[-642.88479051]
 [ 336.77263763]
 [4757.25222711]]
used_time:0.094 sec
t0:0.008892778956223805, t1:-0.6197763356364097
pitch:3.127245270104203, yaw:-0.9022573655990189, roll:-0.013633836009506366
Y:179, X:-51, Z:0
Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.8212852 ]
 [ 0.00653609]
 [-1.42161431]]
Translation Vector:
 [[-639.48129139]
 [ 353.9214528 ]
 [4776.28112056]]
used_time:0.031 sec
t0:0.013880443987146048, t1:-0.5948962139868781
pitch:3.1182643391552527, yaw:-0.9334583566959016, roll:0.007121147462933119
Y:178, X:-53, Z:0
Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.79046883]
 [ 0.03244979]
 [-1.47296701]]
Translation Vector:
 [[-616.1800646 ]
 [ 351.28764716]
 [4654.48726049]]
used_time:0.035 sec
t0:0.002729020557685204, t1:-0.56

Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.83272214]
 [ 0.00437022]
 [-1.3761363 ]]
Translation Vector:
 [[-593.76545159]
 [ 305.17280218]
 [4736.68651939]]
used_time:0.031 sec
t0:0.005718997251738115, t1:-0.6180975916037359
pitch:3.132340337877444, yaw:-0.9044423310195822, roll:0.0014092489569019092
Y:179, X:-51, Z:0
Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.84967855]
 [ 0.00527687]
 [-1.32728099]]
Translation Vector:
 [[-596.63502663]
 [ 303.72014217]
 [4752.68036038]]
used_time:0.036 sec
t0:0.00042376282137916027, t1:-0.6434695095867338
pitch:3.140934094398093, yaw:-0.871773953799616, roll:-0.003396743867710144
Y:179, X:-49, Z:0
Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.78565832]
 [ 0.0401016 ]
 [-1.4554788 ]]
Translation Vector:
 [[-576.79589839]
 [ 293.06589933]
 [4649.2829723 ]]
used_time:0.028 sec
t0:-0.010360793834183616, t1:-0.

t0:0.01807764911719942, t1:-0.5997865247014333
pitch:3.1114616365129084, yaw:-0.9272215981123271, roll:0.002712358816062215
Y:178, X:-53, Z:0
Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.87702515]
 [ 0.04850785]
 [-1.36329427]]
Translation Vector:
 [[-537.92863967]
 [ 352.93664709]
 [4821.84265664]]
used_time:0.032 sec
t0:0.02531520608951092, t1:-0.6326166363158818
pitch:3.1015973311281484, yaw:-0.8852151891412111, roll:-0.014759104566869477
Y:177, X:-50, Z:0
Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.87011522]
 [ 0.05109791]
 [-1.33897683]]
Translation Vector:
 [[-540.88513586]
 [ 353.226151  ]
 [4826.73753987]]
used_time:0.031 sec
t0:0.009832396446774973, t1:-0.6423331914832584
pitch:3.126286534072082, yaw:-0.8731594930094693, roll:-0.028461031161471435
Y:179, X:-50, Z:-1
Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.83094821]
 [ 0.01869106]

Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.87158872]
 [ 0.03748945]
 [-1.26657137]]
Translation Vector:
 [[-595.43001013]
 [ 301.2359102 ]
 [4812.34134211]]
used_time:0.038 sec
t0:-0.012258003672919291, t1:-0.6743239666245515
pitch:-3.1234164440246146, yaw:-0.8305966249522638, roll:-0.0341240010186695
Y:-178, X:-47, Z:-1
Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.97292174]
 [ 0.02823161]
 [-1.12431871]]
Translation Vector:
 [[-622.65300314]
 [ 305.13590726]
 [4933.49487772]]
used_time:0.039 sec
t0:0.02827340584434008, t1:-0.7491654940976493
pitch:3.103870689245283, yaw:-0.7231894693681262, roll:-0.004723105885402488
Y:177, X:-41, Z:0
Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.90265187]
 [ 0.01205473]
 [-1.25663368]]
Translation Vector:
 [[-599.94521182]
 [ 292.18552325]
 [4779.59556569]]
used_time:0.038 sec
t0:0.016629191239754988, t1:-0.

Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.71889298]
 [ 0.02061961]
 [-1.51095659]]
Translation Vector:
 [[-627.88828824]
 [ 216.21162805]
 [4617.98713779]]
used_time:0.031 sec
t0:-0.033529259989913386, t1:-0.5277357800178466
pitch:-3.078143754421631, yaw:-1.0136104301624471, roll:-0.0504005760861905
Y:-176, X:-58, Z:-2
Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.76606653]
 [ 0.03106148]
 [-1.46756052]]
Translation Vector:
 [[-639.22592288]
 [ 222.52231308]
 [4649.79983471]]
used_time:0.029 sec
t0:-0.018278376259141263, t1:-0.5606831333095628
pitch:-3.109004005833822, yaw:-0.9752259820484839, roll:-0.0397417155975189
Y:-178, X:-55, Z:-2
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotati

ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.98433478]
 [ 0.04037649]
 [ 1.03692824]]
Translation Vector:
 [[-505.87944674]
 [ 188.22028123]
 [4716.4400353 ]]
used_time:0.031 sec
t0:0.025399347102889408, t1:-0.7844472735392385
pitch:3.1092253071717084, yaw:0.6683287974910088, roll:-0.038295610204277505
Y:178, X:38, Z:-2
Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.9998095 ]
 [ 0.05791895]
 [ 1.0396155 ]]
Translation Vector:
 [[-513.45706943]
 [ 192.01707682]
 [4816.66592642]]
used_time:0.024 sec
t0:0.04384942504657225, t1:-0.7851101021651024
pitch:3.0857993121207716, yaw:0.665944417

ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: fou

ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: fou

ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: fou

Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.60544336]
 [ 0.15584274]
 [-1.82123243]]
Translation Vector:
 [[-1099.11238341]
 [  118.49050605]
 [ 4521.55937531]]
used_time:0.054 sec
t0:-0.02238248430777142, t1:-0.34453615810872895
pitch:-3.076719704619646, yaw:-1.218277939681276, roll:-0.16475219865597507
Y:-176, X:-69, Z:-9
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.5970054 ]
 [ 0.10140623]
 [-1.85384051]]
Translation Vector:
 [[-1177.57514782]
 [   95.87226737]
 [ 4575.09029873]]
used_time:0.031 sec
t0:0.0044490929464056014, t1:-0.3247113436909044
pitch:3.1278918246979375, yaw:-1.2400575835519323, roll:-0.06827326806070552
Y:179, X:-71, Z:-3
Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.62467542]
 [ 0.09756422]
 [-1.81106855]]
Translation Vector:
 [[-11

ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.82424977]
 [-0.05353544]
 [-1.36800985]]
Translation Vector:
 [[-826.72898149]
 [ 190.58739056]
 [4625.28718706]]
used_time:0.022 sec
t0:0.012161203626713553, t1:-0.6200334389413675
pitch:3.1219813814411412, yaw:-0.9018589989537653, roll:0.047402775786738766
Y:178, X:-51, Z:2
Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.77498951]
 [-0.13513061]
 [-1.41871071]]
Translation Vector:
 [[-851.22677759]
 [ 190.06516383]
 [4662.64405922]]
used_time:0.031 sec
t0:0.019785069454925, t1:-0.5861554549048762
pitch:3.1078515009417034, yaw:-0.9440787852521104, roll:0.11454214463782902
Y:178, X:-54, Z:6
Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.76064779]
 [-0.12677308]
 [-1.42869597]]
Translation Vector:
 [[-855.77528063]
 [

Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.89031479e+00]
 [ 2.78869728e-04]
 [-1.23333003e+00]]
Translation Vector:
 [[-1011.51673896]
 [  258.48439918]
 [ 4448.5773916 ]]
used_time:0.031 sec
t0:0.0007233803203222237, t1:-0.6919289039648371
pitch:3.1405471992770284, yaw:-0.8066384197396967, roll:0.0002531387527126512
Y:179, X:-46, Z:0
Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.78109724]
 [-0.04177029]
 [-1.33686362]]
Translation Vector:
 [[-1034.63767289]
 [  261.32152342]
 [ 4589.21034241]]
used_time:0.036 sec
t0:-0.03834800075727663, t1:-0.6234184004135814
pitch:-3.080157599051842, yaw:-0.8961812902247108, roll:0.0004973350666819275
Y:-176, X:-51, Z:0
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found no face
get_image_points failed
ERROR: found 

Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.67474577]
 [ 0.01225323]
 [-1.68359811]]
Translation Vector:
 [[-1045.06566766]
 [  328.16286213]
 [ 4543.7433822 ]]
used_time:0.031 sec
t0:0.011891255200027618, t1:-0.4323421676621342
pitch:3.1140953171476227, yaw:-1.1235263587507278, roll:0.008145614579663552
Y:178, X:-64, Z:0
Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.79293669]
 [ 0.01848776]
 [-1.32140297]]
Translation Vector:
 [[-836.31442159]
 [ 289.52558778]
 [3798.54822914]]
used_time:0.028 sec
t0:-0.05189823352505851, t1:-0.6331111508263454
pitch:-3.059802190273009, yaw:-0.8824839223421949, roll:-0.05188500729877554
Y:-175, X:-50, Z:-2
ERROR: found no face
get_image_points failed
Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-3.20903095]
 [ 0.04749837]
 [-0.68776752]]
Translation Vector:
 [[-996.49017057]
 [ 319.11253893]
 [4137.05171995]]
use

Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.72693918]
 [ 0.01669925]
 [-1.63065762]]
Translation Vector:
 [[-1020.56262634]
 [  268.99474025]
 [ 4724.98313486]]
used_time:0.038 sec
t0:0.025284716853541594, t1:-0.47275221457943384
pitch:3.0881594850112983, yaw:-1.077617945421053, roll:0.019700403298440198
Y:176, X:-61, Z:1
Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.77568733]
 [-0.03634096]
 [-1.55324342]]
Translation Vector:
 [[-1027.54489177]
 [  264.08305199]
 [ 4702.97249944]]
used_time:0.036 sec
t0:0.04547133750370641, t1:-0.5225403853310531
pitch:3.054791554272615, yaw:-1.0186508379365589, roll:0.0746807607727702
Y:175, X:-58, Z:4
Camera Matrix :[[480.   0. 240.]
 [  0. 480. 180.]
 [  0.   0.   1.]]
Rotation Vector:
 [[-2.9115421 ]
 [-0.10967343]
 [-1.44495749]]
Translation Vector:
 [[-1064.84820938]
 [  264.30425771]
 [ 4794.44846249]]
used_time:0.033 sec
t0:0.1287206457937007, t1:-0

KeyboardInterrupt: 