In [12]:
import cv2
image = cv2.imread("C://Users/HOU/Downloads/example.jpg")
print(image.shape)
cv2.imshow("Image", image)
cv2.waitKey(0)

(1080, 1920, 3)


-1

In [9]:
from pack import SimplePreprocessor

In [20]:
#fake W linear classifier
import numpy as np
import cv2

labels = ["dog","cat","panda"]
np.random.seed(1)

## be *learned* by our model, but for the sake of this example,
W = np.random.randn(3,3072)
b = np.random.randn(3)

#load our example image, resize it and flatten it into our 'feature vector'
orig = cv2.imread('dog1.jpg')
image = cv2.resize(orig, (32, 32)).flatten()

scores = W.dot(image)+b

for (label, score) in zip(labels, scores):
    print ("[INFO] {}: {: .2f}".format(label,score))
    
#draw the label with the highest score on the image as our prediction
cv2.putText(orig,"Label:{}".format(labels[np.argmax(scores)]),(10,30),
            cv2.FONT_HERSHEY_SIMPLEX,0.9,(0,255,0),2)
cv2.imshow("Image",orig)
cv2.waitKey(0)

[INFO] dog:  11343.65
[INFO] cat:  1524.17
[INFO] panda:  2528.56


-1

In [35]:
#Perceptron test
from pack.Perceptron import Perceptron
# construct the OR dataset
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [1]])

print('[INFO] training perceptron...')
p = Perceptron(X.shape[1], alpha = 0.1)
p.fit(X, y, epochs=20)

print('[INFO] testing perceptron...')
      
#loop over the data points
for (x, target) in zip(X, y):
      pred = p.predict(x)
      print('[INFO] data={}, ground-truth={}, pred={}'.format(x, target[0], pred))

[INFO] training perceptron...
[INFO] testing perceptron...
[INFO] data=[0 0], ground-truth=0, pred=0
[INFO] data=[0 1], ground-truth=1, pred=1
[INFO] data=[1 0], ground-truth=1, pred=1
[INFO] data=[1 1], ground-truth=1, pred=1


In [ ]:
#simple NN test
import numpy as np
from CV.nn import neuralnetwork

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

nn = NeuralNetwork([2,2,1],alpha = 0.5)
print(nn)
nn.fit(X,y,epochs=20000)
for (x, target) in zip(X,y):
    pred = nn.predict(x)[0][0]
    step = 1 if pred > 0.5 else 0
    print("[INFO] data={}, ground-truth={}, pred={:.4f}, step={}".format(
    x, target[0], pred, step))

In [2]:
# MNIST
from CV.nn import neuralnetwork
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn import datasets

# load the MNIST and apply mix/max scaling to scale the pixel intensity valeus
# to the range[0,1] (each image is represented by an 8*8 = 64-dim feature vector)

print("[INFO] loading MNIST (sample) dataset...")
digits = datasets.load_digits()
data = digits.data.astype("float")
print(data)
data = (data - data.min()) / (data.max() - data.min())
print("[INFO] sample: {}, dim:{}".format(data.shape[0],data.shape[1]))

(train_X, test_X, train_y, test_y) = train_test_split(data,
                                digits.target, test_size=0.25)

print(train_y)
# one-hot encoding
# convert the labels from intergers to vectors
train_y = LabelBinarizer().fit_transform(train_y)
test_y = LabelBinarizer().fit_transform(test_y)
print(train_y)

# train the network
print("[INFO] training network...")
nn = NeuralNetwork([train_X.shape[1],32,16,10])
print("[INFO] {}".format(nn))
nn.fit(train_X,train_y,epochs=1000)

# evaluate the network
print("[INFO] evluating netword...")
predictions = nn.predict(test_X)
predictions = predictions.argmax(axis = 1)
print(classification_report(test_y.argmax(axis=1),predictions))

[INFO] loading MNIST (sample) dataset...
[[  0.   0.   5. ...,   0.   0.   0.]
 [  0.   0.   0. ...,  10.   0.   0.]
 [  0.   0.   0. ...,  16.   9.   0.]
 ..., 
 [  0.   0.   1. ...,   6.   0.   0.]
 [  0.   0.   2. ...,  12.   0.   0.]
 [  0.   0.  10. ...,  12.   1.   0.]]
[INFO] sample: 1797, dim:64
[0 1 0 ..., 6 8 7]
[[1 0 0 ..., 0 0 0]
 [0 1 0 ..., 0 0 0]
 [1 0 0 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 1 0]
 [0 0 0 ..., 1 0 0]]
[INFO] training network...
[INFO] NeuralNetwork: 64_32_16_10
[INFO] epoch=1, loss=605.4213812
[INFO] epoch=100, loss=6.7841267
[INFO] epoch=200, loss=2.1644860
[INFO] epoch=300, loss=1.5514348
[INFO] epoch=400, loss=0.9078379
[INFO] epoch=500, loss=0.7855177
[INFO] epoch=600, loss=0.2389994
[INFO] epoch=700, loss=0.1867809
[INFO] epoch=800, loss=0.1544959
[INFO] epoch=900, loss=0.1317849
[INFO] epoch=1000, loss=0.1148274
[INFO] evluating netword...
             precision    recall  f1-score   support

          0       1.00      1.00      1.0

Using TensorFlow backend.


[INFO] loading MNIST (full) dataset...


ValueError: Found input variables with inconsistent numbers of samples: [70000, 1797]

In [1]:

import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))


Found GPU at: /device:GPU:0


In [ ]:
import tensorflow as tf
import timeit

# See https://www.tensorflow.org/tutorials/using_gpu#allowing_gpu_memory_growth
config = tf.ConfigProto()
config.gpu_options.allow_growth = True

with tf.device('/cpu:0'):
  random_image_cpu = tf.random_normal((100, 100, 100, 3))
  net_cpu = tf.layers.conv2d(random_image_cpu, 32, 7)
  net_cpu = tf.reduce_sum(net_cpu)

with tf.device('/gpu:0'):
  random_image_gpu = tf.random_normal((100, 100, 100, 3))
  net_gpu = tf.layers.conv2d(random_image_gpu, 32, 7)
  net_gpu = tf.reduce_sum(net_gpu)

gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.333)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))

#sess = tf.Session(config=config)

# Test execution once to detect errors early.
try:
  sess.run(tf.global_variables_initializer())
except tf.errors.InvalidArgumentError:
  print(
      '\n\nThis error most likely means that this notebook is not '
      'configured to use a GPU.  Change this in Notebook Settings via the '
      'command palette (cmd/ctrl-shift-P) or the Edit menu.\n\n')
  raise

def cpu():
  sess.run(net_cpu)
  
def gpu():
  sess.run(net_gpu)
  
# Runs the op several times.
print('Time (s) to convolve 32x7x7x3 filter over random 100x100x100x3 images '
      '(batch x height x width x channel). Sum of ten runs.')
print('CPU (s):')
cpu_time = timeit.timeit('cpu()', number=10, setup="from __main__ import cpu")
print(cpu_time)
print('GPU (s):')
gpu_time = timeit.timeit('gpu()', number=10, setup="from __main__ import gpu")
print(gpu_time)
print('GPU speedup over CPU: {}x'.format(int(cpu_time/gpu_time)))

sess.close()

In [7]:
import tensorflow as tf

hello=tf.constant('Hello,TensorFlow!')

sess=tf.Session()

print(sess.run(hello))

a = tf.random_normal((100,100))
b = tf.random_normal((100,500))
c = tf.matmul(a,b)
sess.run(c)

b'Hello,TensorFlow!'


InternalError: Blas GEMM launch failed : a.shape=(100, 100), b.shape=(100, 500), m=100, n=500, k=100
	 [[Node: MatMul_3 = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](random_normal/RandomStandardNormal, random_normal_1/RandomStandardNormal)]]

Caused by op 'MatMul_3', defined at:
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tornado\platform\asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\asyncio\base_events.py", line 422, in run_forever
    self._run_once()
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\asyncio\base_events.py", line 1434, in _run_once
    handle._run()
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tornado\platform\asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\site-packages\IPython\core\interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-74b07e293ec7>", line 11, in <module>
    c = tf.matmul(a,b)
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\ops\math_ops.py", line 2014, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 4567, in mat_mul
    name=name)
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 3414, in create_op
    op_def=op_def)
  File "C:\Users\HOU\Anaconda3\envs\tensorflow_gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): Blas GEMM launch failed : a.shape=(100, 100), b.shape=(100, 500), m=100, n=500, k=100
	 [[Node: MatMul_3 = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](random_normal/RandomStandardNormal, random_normal_1/RandomStandardNormal)]]


In [6]:
from tensorflow.python.client import device_lib

def get_available_devices():
    local_device_protos = device_lib.list_local_devices()
    return [x.name for x in local_device_protos]

print(get_available_devices())

['/device:CPU:0', '/device:GPU:0']


In [4]:
import numpy
import tensorflow as tf
a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
c = tf.matmul(a, b)
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
print(sess.run(c))

[[22. 28.]
 [49. 64.]]


In [5]:
with tf.device('/cpu:0'):
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
    c = tf.matmul(a, b)
with tf.device('/gpu:0'):
    e = tf.constant([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], shape=[2, 9],dtype=tf.float32, name='e')
    f = tf.matmul(c,e)
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
print(sess.run(f))

[[ 302.  352.  402.  452.  502.  552.  602.  652.  702.]
 [ 689.  802.  915. 1028. 1141. 1254. 1367. 1480. 1593.]]


In [3]:
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.333)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))

